---
layout: post
title: 再次完善自己对Delphi异常处理的理解
categories: delphi之异常处理  软件质量之稳定性 
tags: delphi 异常处理 finally
---

## 回顾以往的学习

以前，自己因为在开发中对Delphi的异常处理机制没有很深入的理解，所以写出了很多在有经验的开发人员这看起来很差劲的代码，所以自己开始结合开发、研究源码总结了一些Delphi异常处理机制的知识，可以参见下面的链接

* [Delphi异常处理的代码逻辑注意点：finally和Continue、Break、Exit](http://www.xumenger.com/delphi-finally-break-continue-exit-20160202/)
* [好的异常处理策略](http://www.xumenger.com/delphi-except-20160128/)
* [再看Delphi的异常处理](http://www.xumenger.com/delphi-except-20160116/)
* [Delphi异常处理时代码的执行逻辑](http://www.xumenger.com/delphi-exception-20151201/)
* [总结一下最近开发遇到的问题，以及最近需要学习的知识点](http://www.xumenger.com/learn-plan-20151123/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception-20150428/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception/)

## 但是还是不够深入

自己的理解还是太死板，不灵活。

比如之前自己总结说

* **try..except..end**：当在`try..except`之间出现异常，那么代码逻辑会跳到`except..end`中，否则`except..end`之间的代码不被执行
* **try..finally..end**：不管`try..finally`之间是不是发生异常，`finally`里面的代码一定会执行

但是这样的总结太口语化，貌似正确，但是还是有误导人的地方，具体可以参见下面的详细的解释说明

## 完善except的解释

当`try..except..end`结构中，在`try..except`之间出现异常时，代码逻辑会跳到`except..end`中，但是只是说会跳到这里，但是不能保证`except..end`之间的代码一定会执行完，因为`except..end`之间也有可能出现异常，导致影响代码的逻辑，所以其实有时候还得再在`except..end`之间再使用`try..except..end`或者`try..finally..end`再做异常保护，这个要看情况灵活选择。

下面通过一个例子展示这种情况的代码运行逻辑，里面的代码逻辑可能绕了一些，但是详细展示的异常处理代码的运行逻辑

```
procedure TForm1.btn1Click(Sender: TObject);
begin
  try
    ShowMessage('1');   //会弹出框
    raise Exception.Create('Test Exception');  //抛出异常
    ShowMessage('2');   //不会弹出框
  except
    on E: Exception do
    begin
      ShowMessage(E.Message);   //会弹出框：'Test Exception'
      ShowMessage('3');         //会弹出框
      try
        try
          ShowMessage('4');         //会弹出框
          raise Exception.Create('Test Exception Again'); //在except..end中抛出异常
          ShowMessage('5')          //不会弹出框
        except
          on E: Exception do
          begin
            ShowMessage(E.Message); //会弹出框：'Test Exception Again'
          end;
        end;
      finally
        ShowMessage('6');           //会弹出框
      end;
    end;
  end;
end;
```

## 完善finally的解释

当`try..finally..end`结构中，无论在`try..finally`之间是否出现异常，代码逻辑最后一定会跳到`finallyt..end`中，但是也只是保证会跳转到这里，但是不能保证`finally..end`之间的代码一定会执行完，因为`finally..end`之间也有可能出现异常，导致影响代码的逻辑，所以其实有时候还得再在`finally..end`之间再使用`try..except..end`或者`try..finally..end`再做异常保护，这个要看情况灵活选择，下面通过一个例子展示这种情况的代码运行逻辑

```
procedure TForm1.btn1Click(Sender: TObject);
begin
  try
    ShowMessage('1');   //会弹出框
    raise Exception.Create('Test Exception');   {抛出异常，但是在下面并没有捕获到这个异常}  
    ShowMessage('2');   //不会弹出框
  finally
    ShowMessage('3');         //会弹出框
    try
      try
        ShowMessage('4');         //会弹出框
        raise Exception.Create('Test Exception Again'); //在except..end中抛出异常
        ShowMessage('5')          //不会弹出框
      except
        on E: Exception do
        begin
          ShowMessage(E.Message); //会弹出框：'Test Exception Again'
        end;
      end;
    finally
      ShowMessage('6');           //会弹出框
    end
  end;

end;
```

别看上面这么复杂的异常处理，结果对于第一个测试异常：raise Exception.Create('Test Exception'); 却没有捕获到。所以，异常处理一定要逻辑清晰，保证所有可能的异常都捕获到，因为虽然有时候，看起来进行了充分的异常处理，但是其实会有一些异常巧妙的避开而导致出现意外。好好理解try..finally..end。因为往往在使用这个结构的时候，需要在try..finally里面使用try..except进行一层异常保护，另外如果有必要也要在finally..end这处再加一层try..except异常保护。总之要灵活使用Delphi的异常机制：try..finally..end和try..except..end

* 或者try..except..end结合try..except..end一起用
* 或者try..except..end结合try..finally..end使用
* 或者try..finally..end结合try..except..end使用
* 以此类推，更为灵活的应用，不要那么死板

要想捕获到第一个异常，需要完善代码逻辑成下面这个样子：

```
procedure TForm1.btn1Click(Sender: TObject);
begin
  try
    try
      ShowMessage('1');   //会弹出框
      raise Exception.Create('Test Exception');  //抛出异常
      ShowMessage('2');   //不会弹出框
    except
      on E: Exception do
      begin
        ShowMessage(E.Message); //会弹出框：'Test Exception'
      end;
    end;
  finally
    ShowMessage('3');         //会弹出框
    try
      try
        ShowMessage('4');         //会弹出框
        raise Exception.Create('Test Exception Again'); //在except..end中抛出异常
        ShowMessage('5')          //不会弹出框
      except
        on E: Exception do
        begin
          ShowMessage(E.Message); //会弹出框：'Test Exception Again'
        end;
      end;
    finally
      ShowMessage('6');           //会弹出框
    end
  end;

end;
```

自己最好实验一下，去感性的感受一下

所以异常处理也并没有看上去的那么简单，对于很多细节还是要充分考虑的，真的是“细节决定成败”，要做到充分的异常处理以保证项目的稳健性，还是有很高的技术含量的！

## 补充

因为Delphi没有try..except..finally..end的结构，所以一般需要将try..except..end和try..finally..end灵活的结合运用，其实上面的两部分的解释就是展示了要将其结合起来用

* 或者try..except..end结合try..except..end一起用
* 或者try..except..end结合try..finally..end使用
* 或者try..finally..end结合try..except..end使用
* 以此类推，更为灵活的应用，不要那么死板

再次推荐

* [Delphi异常处理的代码逻辑注意点：finally和Continue、Break、Exit](http://www.xumenger.com/delphi-finally-break-continue-exit-20160202/)
* [好的异常处理策略](http://www.xumenger.com/delphi-except-20160128/)
* [再看Delphi的异常处理](http://www.xumenger.com/delphi-except-20160116/)
* [Delphi异常处理时代码的执行逻辑](http://www.xumenger.com/delphi-exception-20151201/)
* [总结一下最近开发遇到的问题，以及最近需要学习的知识点](http://www.xumenger.com/learn-plan-20151123/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception-20150428/)
* [Delphi中的异常处理](http://www.xumenger.com/delphi-exception/)
